server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/inventory_sales_db
    username: root
    password: pass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: InventorySalesManager

app:
  jwt-secret: YourSuperSecretKeyMustBeAtLeast32CharactersLong!
  jwt-expiration-ms: 3600000
  allowed-ips:
    - 127.0.0.1
    - 192.168.1.100

logging:
  level:
    org.springframework.security: DEBUG
